### ISSUE TITLE
Authorization and auth header

### ISSUE THREAD

**Issue by JohnWickKeanue** [astravaganza/aha-dl#2]
How to get this headers....

**Comment by astravaganza** [comment]
in the request headers of the call to https://device-register-service.api.aha.firstlight.ai/device/app/register in your browser.

**Comment by JohnWickKeanue** [comment]
any screen shot for authorization header ex: header

**Comment by munnadaniels** [comment]
> 

Didn't get u bro

**Comment by astravaganza** [comment]
![image](https://user-images.githubusercontent.com/83530103/166317710-8ef5630e-c699-4790-ae91-c2f4841d143e.png)

**Comment by JohnWickKeanue** [comment]
403 error in my browser 😢

**Comment by munnadaniels** [comment]
> ![image](https://user-images.githubusercontent.com/83530103/166317710-8ef5630e-c699-4790-ae91-c2f4841d143e.png) ![image](https://user-images.githubusercontent.com/83530103/166318189-d63d2976-51dc-4a2b-b319-f047fb0c4b24.png)

![IMG_20220503_150305](https://user-images.githubusercontent.com/84600096/166432178-3760762b-6b37-4462-a0d7-a4e3c291887d.jpg)


access Denied?

**Comment by Uploader45** [comment]
Getting this error bro any idea - 'x-authorization': auth,
NameError: name 'auth' is not defined
